#pragma once

#include "/Engine/Public/Platform.ush"

RWTexture3D<float> OutVolume;
uint Resolution;
float3 Scale;
float3 Origin;
float3 Location;
float Radius;

[numthreads(4, 4, 4)]
void BloodField(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    if (any(DispatchThreadID >= Resolution))
        return;
    
    const float3 UVW = (float3(DispatchThreadID) + 0.5) / Resolution;
    
    const float3 Position = (UVW - 0.5) * Scale + Origin;
    const float Distance = length(Position - Location);
    const float Mask = 1.0f - saturate(Distance / Radius);
    
    OutVolume[DispatchThreadID] = Mask;
}