#pragma once

#include "/Engine/Public/Platform.ush"

RWTexture3D<float> OutVolume;
int3 Resolution;
float3 Scale;
float3 Origin;
float3 Location;
float Radius;

[numthreads(4, 4, 4)]
void BloodField(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    if (any(DispatchThreadID >= uint3(Resolution)))
        return;
    
    const float3 UVW = (float3(DispatchThreadID) + 0.5) / float3(Resolution);
    
    const float3 Position = (UVW - 0.5) * Scale + Origin;
    const float Distance = length(Position - Location);
    const float Mask = 1.0f - smoothstep(0.9, 1.0, Distance / Radius);
    
    OutVolume[DispatchThreadID] += Mask;
}